version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: # runs not using Workflows must have a `build` job as entry point 
    # directory where steps are run
#     working_directory: ~/circleci-demo-python-django
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
    steps: # steps that comprise the `build` job
      - checkout
      - run:
          command: |
            sudo pip install -U selenium pytest requests
           
      - run:
          command: |
            sudo pwd
      - run:
          name: Running X virtual framebuffer
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true
      - run: 
          command: |
            cd /driver
            
      - run: 
          command: |
            pwd
      - run: 
          command: |
            ls -a
      - run:
          command: |
            sudo pwd
      - run:
          command: |
            pytest
