version: 2.1 # use CircleCI 2.0
orbs:
  browser-tools: circleci/browser-tools@1.0.0
  
jobs: # A basic unit of work in a run
  
  test: # runs not using Workflows must have a `build` job as entry point 
    # directory where steps are run
#     working_directory: ~/circleci-demo-python-django
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
    parallelism: 3
      
    steps: # steps that comprise the `build` job
      - checkout
      - run:
          name: install requirements
          command: |
            sudo pip install -U selenium pytest requests
       
#       - browser-tools/install-browser-tools
   
      - run:
          name: Test
          command: |
            pytest -s -v -m sanity -o junit_family=xunit2 --junitxml=driver/report.xml
      - store_test_results:
            path: driver
   

