version: 2.1

orbs:
  python: circleci/python@0.2.1
  
test:
    steps:
      - run:
          name: Runnning tests
          command: |
            run_test.sh

workflows:
  main:
    jobs:
      - build-and-test
